using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BeGreen.Api.Data;
using BeGreen.Api.Models;
using MongoDB.Driver;

namespace BeGreen.Api.Controllers
{
    [Authorize]
    [ApiController]
    [Route("api/[controller]")]
    public class PettyCashController : ControllerBase
    {
        private readonly MongoDbContext _context;

        public PettyCashController(MongoDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<PettyCash>>> GetRequests()
        {
            var requests = await _context.PettyCashRequests.Find(_ => true).SortByDescending(r => r.RequestDate).ToListAsync();
            return Ok(requests);
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<PettyCash>> GetRequest(string id)
        {
            var request = await _context.PettyCashRequests.Find(r => r.Id == id).FirstOrDefaultAsync();
            if (request == null) return NotFound();
            return Ok(request);
        }

        [HttpPost]
        public async Task<ActionResult<PettyCash>> CreateRequest(PettyCash request)
        {
            request.Id = null; // Ensure ID is generated by MongoDB
            request.RequestDate = DateTime.UtcNow;
            
            await _context.PettyCashRequests.InsertOneAsync(request);
            return CreatedAtAction(nameof(GetRequest), new { id = request.Id }, request);
        }
    }
}
